### ISSUE TITLE
Git finish push develop before master?

### ISSUE THREAD

**Issue by beardyman** [SparkPost/gitplus#3]
Right now `git finish push` will merge and push master before attempting to merge and push develop.  We should probably merge into develop first, that way if there are merge conflicts with develop we don't end up with code in master that isn't in develop.  If we do it in that order, the cmd will bail before attempting to merge into master and we'll never end up with code in master and not develop.  Thoughts?

**Comment by jasonrhodes** [comment]
Hmm. Would you want hotfix code in develop and not in master? Like if the develop build plan is failing on a hotfix I don't even care, that can be fixed post merge... not sure if I understand the problem.

**Comment by colestrode** [comment]
hmm... I see both sides. Philosophically, master should always be a subset of develop, so from that point of view develop should go first.

But practically, if you are merging a hotfix, master is more important than develop. If the merge to master fails, but develop passes, you can't merge develop -> master (because that defeats the purpose of the hotfix). In merging a hotfix, getting master working is the more important, even if it isn't the most "pure".

I vote for keeping the logic as is.

**Comment by beardyman** [comment]
Yeah, I guess that makes sense
